FROM python:3.10-slim-buster

WORKDIR /code

COPY backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./backend .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
